language: go

go:
 - 1.x
 - 1.9.x

install:
 - pwd #just for using vendored dependencies

script:
 - make

after_success:
 - curl --request POST "https://goreportcard.com/checks" --data "repo=github.com/artemnikitin/devicefarm-ci-tool"
