language: go
go: 
 - 1.7.3

script:
 - go test -race -v $(go list ./... | grep -v /vendor/)

after_success:
 - curl --request POST "https://goreportcard.com/checks" --data "repo=github.com/artemnikitin/devicefarm-ci-tool"
